### ISSUE TITLE
sourceMap reference incorrect

### ISSUE THREAD

**Issue by craigs100** [thecarnie/Nivo-Slider-jQuery#2]
jquery.nivoslider-3.3.1.min.js line 4

sourceMap reference should be sourceMappingURL=jquery.nivoslider-3.3.1.min.js.map

**Comment by iam-sysop** [comment]
Thank you!  I will get this rolled in and updated!

**Comment by iam-sysop** [comment]
Issue should be patched with this release: 

https://github.com/thecarnie/Nivo-Slider-jQuery/releases/tag/3.3.2

(NOTE) I made some last-minute changes and re-posted the Release archive - there's a a 45 minute window where the archive downloaded might not be complete - recommend re-verifying most recent download if there are any issues)
